import { describe, expect, it } from "vitest";
import { sanitizeArticleHtml } from "@/lib/blog/sanitize";

describe("sanitizeArticleHtml", () => {
  it("keeps safe article markup and hardens blank-target links", () => {
    const result = sanitizeArticleHtml('<h2>見出し</h2><a href="https://example.com" target="_blank">link</a>');
    expect(result).toContain("<h2>見出し</h2>");
    expect(result).toContain('rel="noopener noreferrer"');
  });

  it("keeps h1 headings generated from microCMS Markdown input", () => {
    const result = sanitizeArticleHtml('<h1 onclick="alert(1)">記事内の見出し</h1>');

    expect(result).toContain(
      "<h1>記事内の見出し</h1>"
    );
    expect(result).not.toContain("onclick");
  });

  it("keeps the safe markup generated by the microCMS rich editor", () => {
    const result = sanitizeArticleHtml(`
      <p>段落と<strong>太字</strong>、<code>inline-code</code></p>
      <ul><li>箇条書き</li></ul><ol><li>番号付きリスト</li></ol>
      <blockquote><p>引用</p></blockquote>
      <pre><code class="language-ts">const answer = 42;</code></pre>
      <figure><img src="https://images.microcms-assets.io/assets/example/image.png" alt="画像"><figcaption>キャプション</figcaption></figure>
      <table><thead><tr><th>見出し</th></tr></thead><tbody><tr><td>セル</td></tr></tbody></table>
    `);

    for (const markup of ["<p>", "<ul>", "<ol>", "<blockquote>", "<pre>", 'class="language-ts"', "<figure>", "<figcaption>", "<table>", "<th>", "<td>"]) {
      expect(result).toContain(markup);
    }
  });

  it("removes executable markup and unsafe URLs", () => {
    const result = sanitizeArticleHtml('<script>alert(1)</script><a href="javascript:alert(1)">bad</a><img src="https://evil.example/image.png">');
    expect(result).not.toContain("script");
    expect(result).not.toContain("javascript:");
    expect(result).not.toContain("evil.example");
  });

  it("allows only microCMS hosted images", () => {
    const result = sanitizeArticleHtml('<img src="https://images.microcms-assets.io/assets/a.png" alt="A">');

    expect(result).toContain("images.microcms-assets.io");
    expect(result).toContain("data-zoomable-image");
    expect(result).toContain('role="button"');
    expect(result).toContain('aria-haspopup="dialog"');
  });
});
