import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import BlogLayout from "@/components/blog/BlogLayout";
import { BlogPostGrid } from "@/components/blog/BlogCards";
import { getPost, getPosts } from "@/lib/blog/client";
import { absoluteUrl, formatDate } from "@/lib/blog/site";
import { sanitizeArticleHtml } from "@/lib/blog/sanitize";

type Props = { params: Promise<{ slug: string }> };
async function postFor(slug: string) { try { return await getPost(slug); } catch { return null; } }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const post = await postFor((await params).slug); if (!post) return {}; const url = absoluteUrl(`/blog/${post.id}`); return { title: `${post.title} | Anzdropブログ`, description: post.excerpt, alternates: { canonical: url }, openGraph: { type: "article", url, title: post.title, description: post.excerpt, publishedTime: post.publishedAt, modifiedTime: post.updatedAt, images: [{ url: post.eyecatch.url, alt: post.eyecatch.alt ?? post.title }] }, twitter: { card: "summary_large_image", title: post.title, description: post.excerpt, images: [post.eyecatch.url] } }; }
export default async function BlogPostPage({ params }: Props) { const post = await postFor((await params).slug); if (!post) notFound(); const related = await getPosts({ filters: `category[equals]${post.category.id}[and]id[not_equals]${post.id}`, limit: 3 }); const url = absoluteUrl(`/blog/${post.id}`); const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: post.title, description: post.excerpt, datePublished: post.publishedAt, dateModified: post.updatedAt, image: post.eyecatch.url, author: { "@type": "Person", name: post.author.name, url: absoluteUrl(`/blog/authors/${post.author.id}`) }, mainEntityOfPage: url };
  return <BlogLayout><article className="mx-auto max-w-3xl space-y-8"><header className="space-y-4"><Link href={`/blog/categories/${post.category.id}`} className="text-xs font-bold text-brand">{post.category.name}</Link><h1 className="text-3xl font-black leading-tight sm:text-4xl">{post.title}</h1><p className="text-sm text-ink/60">公開日: {formatDate(post.publishedAt)}{post.updatedAt !== post.publishedAt ? ` / 更新日: ${formatDate(post.updatedAt)}` : ""}</p><Image src={post.eyecatch.url} alt={post.eyecatch.alt ?? post.title} width={post.eyecatch.width ?? 1200} height={post.eyecatch.height ?? 630} className="w-full rounded-lg object-cover" priority /></header><div className="prose max-w-none text-ink/80" dangerouslySetInnerHTML={{ __html: sanitizeArticleHtml(post.body) }} /><footer className="space-y-4 border-t border-ink/10 pt-6"><div className="flex flex-wrap gap-2">{post.tags.map(tag => <Link key={tag.id} href={`/blog/tags/${tag.id}`} className="rounded bg-ink/[0.06] px-2.5 py-1 text-xs text-ink/70">#{tag.name}</Link>)}</div><Link href={`/blog/authors/${post.author.id}`} className="flex items-center gap-3 rounded-lg border border-ink/10 p-4 hover:bg-ink/[0.03]"><Image src={post.author.image.url} alt="" width={48} height={48} className="h-12 w-12 rounded-full object-cover" /><span><span className="block text-xs text-ink/50">著者</span><span className="font-bold">{post.author.name}</span></span></Link></footer></article>{related.contents.length > 0 && <section className="mx-auto mt-14 max-w-6xl space-y-5"><h2 className="text-xl font-black">関連記事</h2><BlogPostGrid posts={related.contents} /></section>}<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /></BlogLayout>; }
